### ISSUE TITLE
Furca

### ISSUE THREAD

**Issue by elvisnovelo** [philippe-bachour/vr_charting#1]
1. This periodontal chart do not display the furca, you can use this chart like a guide http://www.periodontalchart-online.com or http://www.periodontalchart-online.com/fr/ for your lenguage

2. Use a color's to indicate bleeding and plaque

3. Missing tooths (Use something like "/" to indicate a missing tooth)

**Comment by hypoconulide** [comment]
It's work in progress, that's why some features are missing.
The problem with periodontalchart-online is that it uses flash : performances are awful, and browsers are slowly deprecating flash...
Thank you for your feedback !

**Comment by elvisnovelo** [comment]
Nice, do you will release the updates or are they proprietary?

**Comment by hypoconulide** [comment]
Yes the updates will be released here and on my github pages so everybody can use it, it won't go proprietary.
